# This test contains a route with a cyclic reference to itself (so it is dropped).
#
# Input:
# - Parent infra/example-route:
#   - Delegate /a to routes in "a" namespace
#   - Everything else goes to infra/example-svc
# - Child a/route-a:
#   - /a/1 goes to a/svc-a
#   - Delegate /a/b to route a/route-a
#
# Expected output routes:
# - /a/1 -> a/svc-a
# - /* -> infra/example-svc
# - no route for /a/b because of cyclic reference
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route
  namespace: infra
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "example.com"
  rules:
  - backendRefs:
    - name: example-svc
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /a
    backendRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: "*"
      namespace: a
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-a
  namespace: a
spec:
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /a/1
    backendRefs:
    - name: svc-a
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /a/b
    backendRefs:
    # Cyclic reference to itself
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: "route-a"
      namespace: a
