# This test contains a parent route that delegates to two child routes, and both
# of the child routes delegate to a common grandchild route. The two children
# and one grandchild routes all have the inherit-parent-matcher annotation set to
# true.
#
# Input:
# - Parent infra/api-example-com:
#   - Delegate /api1 to default/apiproduct-1
#   - Delegate /api2 to default/apiproduct-2
# - Child default/apiproduct-1 (with annotation inherit-parent-matcher=true):
#   - / delegates to default/httpbin
# - Child default/apiproduct-2 (with annotation inherit-parent-matcher=true):
#   - / delegates to default/httpbin
# - Grandchild default/httpbin (with annotation inherit-parent-matcher=true):
#   - / goes to svc default/httpbin
#
# Expected output routes:
# - /api1 -> default/httpbin
# - /api2 -> default/httpbin
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-example-com
  namespace: infra
  labels:
    app: apis
spec:
  parentRefs:
    - name: example-gateway
  hostnames:
    - "api.example.com"
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /api1
      backendRefs:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        name: apiproduct-1
        namespace: default
    - matches:
      - path:
          type: PathPrefix
          value: /api2
      backendRefs:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        name: apiproduct-2
        namespace: default
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: apiproduct-1
  namespace: default
  labels:
    app: apis
  annotations:
    delegation.kgateway.dev/inherit-parent-matcher: "true"
spec:
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /
      backendRefs:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        name: httpbin
        namespace: default
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: apiproduct-2
  namespace: default
  labels:
    app: apis
  annotations:
    delegation.kgateway.dev/inherit-parent-matcher: "true"
spec:
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /
      backendRefs:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        name: httpbin
        namespace: default
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin
  namespace: default
  labels:
    app: apis
  annotations:
    delegation.kgateway.dev/inherit-parent-matcher: "true"
spec:
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
      - name: httpbin
        namespace: default
        port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 8000
