# This test contains a parent route that delegates to a child route. A traffic policy with transformation
# config targets the parent route, and a traffic policy with rate limit config targets the child route.
# The resulting child route should contain both the transformation and rate limit policy.
#
# Input:
# - Parent infra/example-route:
#   - Delegate /a to routes in "a" namespace
#   - Everything else goes to infra/example-svc
# - Child a/route-a:
#   - /a/1 goes to a/svc-a
# - TrafficPolicy infra/example-policy:
#   - specifies response transformation
#   - targetRef points to infra/example-route
# - TrafficPolicy a/route-a-policy:
#   - specifies local rate limit
#   - targetRef points to a/route-a
#
# Expected output routes:
# - /a/1 -> a/svc-a, has transformation specified by infra/example-policy and rate limit
#   specified by a/route-a-policy
# - /* -> infra/example-svc, has transformation specified by infra/example-policy
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route
  namespace: infra
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "example.com"
  rules:
  - backendRefs:
    - name: example-svc
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /a
    backendRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: "*"
      namespace: a
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-a
  namespace: a
spec:
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /a/1
    backendRefs:
    - name: svc-a
      port: 8080
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: example-policy
  namespace: infra
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: example-route
  transformation:
    response:
      add:
      - name: abc
        value: custom-value-abc
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: route-a-policy
  namespace: a
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: route-a
  rateLimit:
    local:
      tokenBucket:
        maxTokens: 99
        tokensPerFill: 1
        fillInterval: 33s